refactor so jump menu does not appear if no id
elifesciences/enhanced-preprints-client pull request #579
Opened 2023-04-13 11:00 UTC by discodavey

2023-04-13 14:09 UTC, scottaubrey commented
Actually - 1 last comment: we should probably add a test for this behaviour

2023-04-13 14:10 UTC, scottaubrey requested changes
We should probably create a test for this.

2023-04-14 08:37 UTC, discodavey commented
@scottaubrey Added test

2023-04-14 08:57 UTC, scottaubrey approved these changes

2023-04-14 08:58 UTC, merged